export function Document(): void;
export * from "./shared/facades.js";
export * from "./shared/html-classes.js";
export { CustomEvent } from "./interface/custom-event.js";
export { Event } from "./interface/event.js";
export { EventTarget } from "./interface/event-target.js";
export { InputEvent } from "./interface/input-event.js";
export { NodeList } from "./interface/node-list.js";
export function parseHTML(html: any, global?: {}): any;
import { DOMParser } from "./dom/parser.js";
import { WINDOW } from "./shared/symbols.js";
export { DOMParser, WINDOW };
export { parseJSON, toJSON } from "./shared/parse-json.js";
